### PR TITLE
curl: reduce docker size

### PR DESCRIPTION
**Pull request by glimchb**
```
$ docker images | grep "3.10.8-slim\|7.85.0"
python           3.10.8-slim  b05ccb7cc132   16 hours ago   126MB
curlimages/curl  7.85.0       dddbb581f872    6 weeks ago   15.2MB
```

Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

### CODE REVIEW

**Review by seroyer — APPROVED** [review]
Very nice, but I think you want docker.io/curlimages/curl

**Comment by glimchb** [comment]
> Very nice, but I think you want docker.io/curlimages/curl

thanks, fixed

**Comment by glimchb** [comment]
checking error:
```
+ docker-compose exec -T agent curl -X POST --data @/tmp/input.json -H Content-Type:application/yang-data+json --user my-serial-number:my-secret --key /private_key.pem --cert /my_cert.pem --cacert /opi.pem https://bootstrap:9090/restconf/operations/ietf-sztp-bootstrap-server:get-bootstrapping-data
+ tee /tmp/post_rpc_input.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (58) unable to set private key file: '/private_key.pem' type PEM
```

**Comment by glimchb** [comment]
> checking error:
> 
> ```
> + docker-compose exec -T agent curl -X POST --data @/tmp/input.json -H Content-Type:application/yang-data+json --user my-serial-number:my-secret --key /private_key.pem --cert /my_cert.pem --cacert /opi.pem https://bootstrap:9090/restconf/operations/ietf-sztp-bootstrap-server:get-bootstrapping-data
> ...
> curl: (58) unable to set private key file: '/private_key.pem' type PEM
> ```

found it. due to permissions of `/private_key.pem`

**Pull request merged**
