### PR TITLE
refactor: move checksum calculation to utils

### PR DESCRIPTION
**Pull request by h0lyalg0rithm**
## Proposed changes

Move sha256 calculation to utils.go file.
Add tests to validate change

## Types of changes

What types of changes does your code introduce to the repo? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by glimchb — APPROVED** [review]
@h0lyalg0rithm this is great, please fix small gosec issue

**Comment by glimchb** [comment]
@h0lyalg0rithm in a separate PR , not here,  wdyt to move `downloadAndValidateImage(), copyConfigurationFile(), launchScriptsConfiguration()` to a new file... ? it looks not belonging to `daemon.go`

**Comment by h0lyalg0rithm** [comment]
> @h0lyalg0rithm in a separate PR , not here, wdyt to move `downloadAndValidateImage(), copyConfigurationFile(), launchScriptsConfiguration()` to a new file... ? it looks not belonging to `daemon.go`

I think we should update the golinter version as it displays the line with the issue in the github action run.Here is the output 
https://github.com/h0lyalg0rithm/sztp/actions/runs/10222129019/job/28286107496

**Comment by h0lyalg0rithm** [comment]
> @h0lyalg0rithm in a separate PR , not here, wdyt to move `downloadAndValidateImage(), copyConfigurationFile(), launchScriptsConfiguration()` to a new file... ? it looks not belonging to `daemon.go`

Yes it makes sense to move them

**Comment by glimchb** [comment]
> I think we should update the golinter version

sure, go for it

**Pull request merged**
