### PR TITLE
ci: add go testing

### LINKED ISSUE #42: add go testing to `sztp-agent`

### PR DESCRIPTION
**Pull request by glimchb**
Fixes #42

Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

### CODE REVIEW

**Review by alknopfler — APPROVED** [review]
LGTM

**Comment by glimchb** [comment]
> LGTM

why 
```
#29 97.41     --- FAIL: TestAgent_doRequestBootstrapServer/Test_OK_passing_all_the_information (20.02s)
```
here https://github.com/opiproject/sztp/actions/runs/3257608744/jobs/5348970782

**Comment by alknopfler** [comment]
I need to check it with more time...it's late ;)

**Comment by alknopfler** [comment]
the error is:
image
I think is due to the new protocol added...
Let me check it and test it again

**Comment by glimchb** [comment]
@alknopfler yes, because Bootstrap server returns data in CMS encoded format, not plain JSON

**Review by alknopfler — APPROVED** [review]
LGTM

**Comment by glimchb** [comment]
re-basing after https://github.com/opiproject/sztp/pull/67 merged

**Pull request merged**
