### PR TITLE
replace progress message

### LINKED ISSUE #333: replace progress message `message sent via JSON` with something more meaningful
example:
```
sztp-agent-1           | 2024/06/07 00:16:24 [INFO] Configuration file copied successfully
sztp-agent-1           | 2024/06/07 00:16:24 [INFO] Starting the pre-configuration.
sztp-agent-1           | 2024/06/07 00:16:24 [INFO] Starting the Report Progress request.
sztp-agent-1           | 2024/06/07 00:16:24 [INFO] Sending to: https://bootstrap:9090/restconf/operations/ietf-sztp-bootstrap-server:report-progress
sztp-agent-1           | 2024/06/07 00:16:24 [INFO] Sending input: {"ietf-sztp-bootstrap-server:input":{"progress-type":"pre-script-initiated","message":"message sent via JSON"}}
sztp-agent-1           | 2024/06/07 00:16:24 [ERROR]  [ERROR] Status code received: 204 ...but status code expected: 200
sztp-agent-1           | 2024/06/07 00:16:24 [INFO] pre-configuration script created successfully
```

code https://github.com/opiproject/sztp/blob/5461c97dc1b0782d3d27ed643b5b0f6dfffb5705/sztp-agent/pkg/secureagent/daemon.go#L99

### PR DESCRIPTION
**Pull request by mohamedasifs123**
closes #333

### CODE REVIEW

**Review by glimchb — CHANGES_REQUESTED** [review]
This is not right 
Each place that calls function need to pass it’s own message

**Comment by Xeckt** [comment]
I'm not a reviewer by any means but a small nitpick about the commits, try and describe in a short way what you've done with the commit. All your commit messages are the same so it would be hard to discern which is which at a later time if need be.

**Comment by glimchb** [comment]
1. golangci is failing on `  Error: File is not `gofmt`-ed with `-s` (gofmt)`
2. commitliont is failing (i think on the first commit) - you can squash all commits now and fix the message

**Comment by mohamedasifs123** [comment]
I will do squash commit

**Comment by glimchb** [comment]
@mohamedasifs123 looks good, please squash so we pass `Commitlint` checker

Also please consider moving `doReportProgress()` to https://github.com/opiproject/sztp/blob/main/sztp-agent/pkg/secureagent/progress.go

**Comment by mohamedasifs123** [comment]
Okay @glimchb 
I will move the function.

**Comment by glimchb** [comment]
@mohamedasifs123 great work, looks correct to me now...

please add space ` ` between `fix: message` in the commit message of both commits to pass `commitlint` and we can merge this

**Comment by mohamedasifs123** [comment]
Yeah, thanks for suggesting local check of commitlint

**Review by glimchb — APPROVED** [review]
great, ready for merge

**Pull request merged**
