### PR TITLE
add ProgressType enum

### PR DESCRIPTION
**Pull request by glimchb**
Related to #65

Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

### CODE REVIEW

**Review by PWAlessi — COMMENTED** [review]
Looks good. I also lament Go not having an `enum`

**Comment by glimchb** [comment]
> Looks good. I also lament Go not having an `enum`

I google a bit and there are few auto-generations for this... I just manually created this...

**Comment by alknopfler** [comment]
Welcome to go ;) but I also usually do manually

**Review by alknopfler — APPROVED** [review]
LGTM

**Pull request merged**
